[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description = ""

[tool.poetry.dependencies]
pandas = "^2.0"
python = "^3.9"
seaborn = "^0.13.0"
matplotlib = "^3.8.2"
numpy = "^1.26.2"
